#!/usr/bin/env bash
# setup-configs.sh — inject kernel configs into defconfig
# env: KSU_TYPE, SOURCE_TYPE, DEFCONFIG (full path), KERNEL_DIR
set -e

: "${KSU_TYPE:?}"
: "${SOURCE_TYPE:?}"
: "${DEFCONFIG:?}"
: "${KERNEL_DIR:?}"

CF="$DEFCONFIG"

# ── Base cleanup ────────────────────────────────────────────────────────────
sed -i 's/ cgroup_disable=pressure//'                    "$CF"
sed -i 's/CONFIG_CMDLINE="/&slub_debug=- page_owner=off /' "$CF"

# ── Common configs (all variants, both GKI + CLO) ───────────────────────────
cat >> "$CF" << 'EOF'
CONFIG_OVERLAY_FS=y
CONFIG_OVERLAY_FS_REDIRECT_DIR=y
CONFIG_OVERLAY_FS_REDIRECT_ALWAYS_FOLLOW=y
CONFIG_OVERLAY_FS_INDEX=y
CONFIG_OVERLAY_FS_XINO_AUTO=y
CONFIG_OVERLAY_FS_METACOPY=y
CONFIG_TMPFS_XATTR=y
CONFIG_TMPFS_POSIX_ACL=y
CONFIG_TCP_CONG_ADVANCED=y
CONFIG_TCP_CONG_BBR=y
CONFIG_TCP_CONG_WESTWOOD=y
CONFIG_TCP_CONG_VEGAS=y
CONFIG_TCP_CONG_YEAH=y
CONFIG_TCP_CONG_VENO=y
CONFIG_TCP_CONG_BIC=n
CONFIG_TCP_CONG_HTCP=n
CONFIG_DEFAULT_WESTWOOD=y
CONFIG_IP_NF_TARGET_TTL=y
CONFIG_IP6_NF_TARGET_HL=y
CONFIG_IP6_NF_MATCH_HL=y
CONFIG_IP6_NF_NAT=y
CONFIG_IP_SET=y
CONFIG_IP_SET_MAX=65534
CONFIG_IP_SET_BITMAP_IP=y
CONFIG_IP_SET_BITMAP_IPMAC=y
CONFIG_IP_SET_BITMAP_PORT=y
CONFIG_IP_SET_HASH_IP=y
CONFIG_IP_SET_HASH_IPMARK=y
CONFIG_IP_SET_HASH_IPPORT=y
CONFIG_IP_SET_HASH_IPPORTIP=y
CONFIG_IP_SET_HASH_IPPORTNET=y
CONFIG_IP_SET_HASH_IPMAC=y
CONFIG_IP_SET_HASH_MAC=y
CONFIG_IP_SET_HASH_NETPORTNET=y
CONFIG_IP_SET_HASH_NET=y
CONFIG_IP_SET_HASH_NETNET=y
CONFIG_IP_SET_HASH_NETPORT=y
CONFIG_IP_SET_HASH_NETIFACE=y
CONFIG_IP_SET_LIST_SET=y
CONFIG_ZRAM_WRITEBACK=y
# CONFIG_ZRAM_MEMORY_TRACKING is not set
CONFIG_LRU_GEN=y
CONFIG_LRU_GEN_ENABLED=y
CONFIG_NET_SCH_FQ=y
CONFIG_NET_SCH_CAKE=y
CONFIG_WQ_POWER_EFFICIENT_DEFAULT=y
# CONFIG_SLUB_DEBUG_ON is not set
# CONFIG_SLUB_STATS is not set
# CONFIG_DEBUG_LIST is not set
# CONFIG_DEBUG_MEMORY_INIT is not set
# CONFIG_RCU_TRACE is not set
# CONFIG_PRINTK_CALLER is not set
# CONFIG_DEBUG_FS is not set
# CONFIG_F2FS_IOSTAT is not set
# CONFIG_NTSYNC is not set
EOF

# ── Wild-KSU specific ────────────────────────────────────────────────────────
if [ "$KSU_TYPE" = "wild" ]; then
  cat >> "$CF" << 'EOF'
CONFIG_KSU=y
CONFIG_KSU_SUSFS=y
CONFIG_KSU_SUSFS_SUS_MAP=y
CONFIG_KSU_SUSFS_SUS_PATH=y
CONFIG_KSU_SUSFS_SUS_MOUNT=y
CONFIG_KSU_SUSFS_SUS_KSTAT=y
CONFIG_KSU_SUSFS_SPOOF_UNAME=y
CONFIG_KSU_SUSFS_ENABLE_LOG=y
CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
CONFIG_KSU_SUSFS_SUS_SU=y
CONFIG_BBG=y
EOF

# ── SukiSU specific ─────────────────────────────────────────────────────────
elif [ "$KSU_TYPE" = "suki" ]; then
  cat >> "$CF" << 'EOF'
CONFIG_KSU=y
CONFIG_KSU_SUSFS=y
CONFIG_KSU_SUSFS_SUS_MAP=y
CONFIG_KSU_SUSFS_SUS_PATH=y
CONFIG_KSU_SUSFS_SUS_MOUNT=y
CONFIG_KSU_SUSFS_SUS_KSTAT=y
CONFIG_KSU_SUSFS_SPOOF_UNAME=y
CONFIG_KSU_SUSFS_ENABLE_LOG=y
CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
CONFIG_KSU_SUSFS_SUS_SU=y
CONFIG_KPM=y
EOF

# ── NoKSU — pure vanilla, no KSU/SUSFS/BBG/KPM ─────────────────────────────
# (only common configs above apply — nothing extra here)
fi

# ── NetHunter (CLO-only, opt-in via NETHUNTER=true) ─────────────────────────
if [ "$SOURCE_TYPE" = "clo" ] && [ "$NETHUNTER" = "true" ]; then
  cat >> "$CF" << 'EOF'
# NetHunter: module support
CONFIG_MODULE_FORCE_UNLOAD=y
# NetHunter: BT USB dongle
CONFIG_BT_HCIBTUSB=y
CONFIG_BT_HCIBTUSB_BCM=y
CONFIG_BT_HCIBTUSB_RTL=y
# NetHunter: Wireless base
CONFIG_MAC80211=y
CONFIG_MAC80211_MESH=y
CONFIG_MAC80211_LEDS=y
# NetHunter: Atheros / WN722N V1 (AR9271)
CONFIG_WLAN_VENDOR_ATH=y
CONFIG_ATH9K_HTC=y
CONFIG_CARL9170=y
CONFIG_ATH6KL=y
CONFIG_ATH6KL_USB=y
# NetHunter: Ralink RT2X00
CONFIG_WLAN_VENDOR_RALINK=y
CONFIG_RT2X00=y
CONFIG_RT2500USB=y
CONFIG_RT73USB=y
CONFIG_RT2800USB=y
CONFIG_RT2800USB_RT33XX=y
CONFIG_RT2800USB_RT35XX=y
CONFIG_RT2800USB_RT3573=y
CONFIG_RT2800USB_RT53XX=y
CONFIG_RT2800USB_RT55XX=y
CONFIG_RT2800USB_UNKNOWN=y
# NetHunter: Mediatek
CONFIG_WLAN_VENDOR_MEDIATEK=y
CONFIG_MT7601U=y
# NetHunter: Realtek RTW88
CONFIG_WLAN_VENDOR_REALTEK=y
# CONFIG_RTL8187 is not set
# CONFIG_RTL_CARDS is not set
# CONFIG_RTL8192CU is not set
# CONFIG_RTL8XXXU_UNTESTED is not set
# CONFIG_88XXAU is not set
CONFIG_RTW88=m
CONFIG_RTW88_CORE=m
CONFIG_RTW88_USB=m
CONFIG_RTW88_88XXA=m
CONFIG_RTW88_8821A=m
CONFIG_RTW88_8821AU=m
CONFIG_RTW88_LEDS=y
# CONFIG_RTW88_DEBUG is not set
# CONFIG_RTW88_DEBUGFS is not set
# NetHunter: Zydas
CONFIG_WLAN_VENDOR_ZYDAS=y
CONFIG_USB_ZD1201=y
CONFIG_ZD1211RW=y
CONFIG_USB_NET_RNDIS_WLAN=y
# NetHunter: USB gadget additions
CONFIG_USB_CONFIGFS_RNDIS=y
CONFIG_USB_CONFIGFS_OBEX=y
CONFIG_USB_CONFIGFS_ECM_SUBSET=y
# NetHunter: SDR
CONFIG_MEDIA_DIGITAL_TV_SUPPORT=y
CONFIG_MEDIA_SDR_SUPPORT=y
CONFIG_USB_AIRSPY=y
CONFIG_USB_HACKRF=y
CONFIG_USB_MSI2500=y
# CONFIG_MEDIA_SUBDRV_AUTOSELECT is not set
CONFIG_DVB_RTL2830=y
CONFIG_DVB_RTL2832=y
CONFIG_DVB_RTL2832_SDR=y
CONFIG_DVB_SI2168=y
CONFIG_DVB_ZD1301_DEMOD=y
EOF
  echo "[OK] NetHunter configs applied (CLO)"
fi

echo "[OK] Configs written for KSU_TYPE=$KSU_TYPE SOURCE_TYPE=$SOURCE_TYPE"
