name: "🔨 Build Kernel — Creek Test"

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-kernel.yml
    with:
      variant_name:  "CLO-Creek-Test"
      source_type:   "creek"
      ksu_type:      "ksun"
      zip_prefix:    "CLO_Creek_Test"
      artifact_name: "clo-creek-test"
      defconfig:     "gki_defconfig"
      clo_fragment:  "vendor/bengal_GKI.config vendor/creek_GKI.config"
      build_type:    "testing"
    secrets: inherit
